### ISSUE TITLE
Nonexist start path listing and empty directory previewing both lead to panic, version v1.9.0

### ISSUE THREAD

**Issue by rustyhu** [antonmedv/walk#142]
**Nonexist start path listing:**

```
~> walk kkk
Caught panic:

runtime error: makeslice: len out of range

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        /usr/lib/go-1.21/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        /usr/lib/go-1.21/src/runtime/debug/stack.go:16 +0x13
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
        /somepath/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.26.5/tea.go:479 +0x91
panic({0x558e40?, 0x5c2cf0?})
        /usr/lib/go-1.21/src/runtime/panic.go:920 +0x270
main.(*model).View(0xc00015c000)
        /somepath/walk/main.go:486 +0x2cb
github.com/charmbracelet/bubbletea.(*Program).Run(0xc00015e000)
        /somepath/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.26.5/tea.go:534 +0x964
main.main()
        /somepath/walk/main.go:132 +0x525
```

**Empty directory previewing:**
```
Caught panic:

runtime error: makeslice: len out of range

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        /usr/lib/go-1.21/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        /usr/lib/go-1.21/src/runtime/debug/stack.go:16 +0x13
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
        /somepath/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.26.5/tea.go:479 +0x91
panic({0x558e40?, 0x5c2cf0?})
        /usr/lib/go-1.21/src/runtime/panic.go:920 +0x270
main.(*model).preview(0xc000180000)
        /somepath/walk/main.go:777 +0x1c5
main.(*model).View(0xc000180000)
        /somepath/walk/main.go:467 +0x15f
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc000184000, {0x5c3c98?, 0xc000180000?}, 0x5?)
        /somepath/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.26.5/tea.go:414 +0x8ad
github.com/charmbracelet/bubbletea.(*Program).Run(0xc000184000)
        /somepath/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.26.5/tea.go:550 +0xaf2
main.main()
        /somepath/walk/main.go:132 +0x525
```

Both lead to invalid `rows` number returned from algorithm of `wrap()`, which are used in `make([]string, rows)`,
then lead to `runtime error: makeslice: len out of range`.

**Comment by oderwat** [comment]
Got this one too when trying 'walk' the first time today.

**Comment by antonmedv** [comment]
Fixed.
