### ISSUE TITLE
Command line option: "--icons" crashes

### ISSUE THREAD

**Issue by ProgrammingLife** [antonmedv/walk#85]
```
$ llama --version
   llama  v1.4.0

$ llama --icons

panic: open /home/guest/apps/llama/--icons: no such file or directory

goroutine 1 [running]:
main.(*model).list(0xc000146000)
	/home/runner/work/llama/llama/main.go:631 +0x2d6
main.main()
	/home/runner/work/llama/llama/main.go:97 +0x19b
```
Is it hard-coded path?

I'm using Ubuntu, prebuilt binary of LLama.

**Comment by dlvhdr** [comment]
Yeah it needs a new release

**Comment by antonmedv** [comment]
Fixed.
