### ISSUE TITLE
Command line option "--icons" crashes in PowerShell

### ISSUE THREAD

**Issue by tayopi** [antonmedv/walk#87]
```
PS C:\> llama --version

  llama v1.4.0

PS C:\> llama --icons
panic: open C:\--icons: The system cannot find the file specified.

goroutine 1 [running]:
main.(*model).list(0xc000158000)
        /home/runner/work/llama/llama/main.go:631 +0x2d6
main.main()
        /home/runner/work/llama/llama/main.go:97 +0x19b
PS C:\>
```

I'm using llama_windows_amd64.exe

**Comment by tayopi** [comment]
This issue seems to be fixed in [release v1.5.2](https://github.com/antonmedv/walk/releases/tag/v1.5.2)
