### ISSUE TITLE
option --icons crashes if a directory is specified

### ISSUE THREAD

**Issue by sol2070** [antonmedv/walk#90]
I'm on Arch Linux, with Fish terminal. If I use the `--icons` option together with a directory, for example:
```
walk --icons /directory
```
the program crashes with this error:
```
panic: open /home/username/--icons: no such file or directory

goroutine 1 [running]:
main.(*model).list(0xc0001ce000)
	/home/runner/work/walk/walk/main.go:593 +0x2d6
main.main()
	/home/runner/work/walk/walk/main.go:101 +0x27b
```
Thanks for this great program!

**Comment by antonmedv** [comment]
Fixed in 1.15.2
